name: 'Flutter Build and Test'

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --machine > test-results.json

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        permissions:
          checks: write
          pull-requests: write
        if: always()
        with:
          files: |
            test-results.json

