name: 'Flutter Build and Test'

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          flags: unittests
          name: codecov-upload
          fail_ci_if_error: true

      - name: Run tests for the report
        run: flutter test --coverage --machine > test_results.json

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()  
        with:
          name: Flutter
          path: test_results.json
          reporter: flutter-json
