name: Flutter Build and Test with Report

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: coverage/lcov.info

  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download test results artifact
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Flutter Tests
          path: '*.info'
          reporter: 'flutter-json'
          fail-on-error: 'true'
