name: Flutter Test

on:
  push:
  pull_request:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter pub get
      - run: mkdir -p test/reports 
      - run: flutter test > test/reports/test-results.json

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Flutter Tests
          path: test/reports/test-results.json
          reporter: flutter-json
