name: 'Test Result'

on:
  workflow_run:
    workflows: ['Flutter Build']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Flutter Tests
          path: test-results.json
          reporter: flutter-json
